#!/usr/bin/env sh

set -e

config_file="webpack.prod.js"

# create dist if it doesn't exist
mkdir -p dist

# try to clean dist
rm -rf dist/*

# build project with webpack
webpack -p --config $config_file

# copy public files
cp public/* dist

echo "Project has been built in 'dist' directory."
