#!/usr/bin/env sh

set -e

config_file="webpack.dev.js"

# create dist if it doesn't exist
mkdir -p dist

# try to clean dist
rm -rf dist/*

# build project with webpack
webpack -d --config $config_file

# copy public files
cp public/* dist

# run development web server
exec webpack-dev-server --config $config_file
